### PR TITLE
Disable sounds for autocomplete suggestions

### PR DESCRIPTION
**Pull request by Andre9642**
Hello Derek,
I personally don't like the sounds played when autocomplete suggestions appear. So, I suggest you an option to disable this.
Hoping not to have made mistakes...

### CODE REVIEW

**Comment by derekriemer** [comment]
This already can be done.

1. In NVDA's configuration, open object presentation.
2. Disable Play a sound when auto-suggestions appear.

Now, sounds will stop playing for suggestions. You can also use a config profile for the app to do this on a per-app basis if you like. The approach in this PR will stop the open/closed behavior completely, which is not guaranteed to stop only sounds (Imagine an addon which vibrated a touch screen device on suggestion open).

**Comment by derekriemer** [comment]
I do really appreciate the work though.

**Comment by Andre9642** [comment]
> The approach in this PR will stop the open/closed behavior completely, which is not guaranteed to stop only sounds (Imagine an addon which vibrated a touch screen device on suggestion open).

Indeed! I however took a look at `event_suggestionsOpened()` and `event_suggestionsClosed()` functions to check what they are doing. At this time, they only play a sound.

> You can also use a config profile for the app to do this on a per-app basis if you like. 

Oh! Why did I not think about it?! O.o

**Comment by derekriemer** [comment]
That's fine, the possibilities catch us all sometimes. Thanks again for the PR, and keep the suggestions coming.

**Pull request closed without merging**
